### MariaDB Test Server ###
spring:
  datasource:
    url: jdbc:mariadb://gtaimages.iptime.org:9001/officesharingtest
    username: ospmstest220725
    password: gta221229

### MariaDB Release Server ###
#spring:
#  datasource:
#    url: jdbc:mariadb://gtaimages.iptime.org:9001/officesharing
#    username: ospms220725
#    password: gta221229
